- name: install nginx packages
  tags: nginx
  package:
    name: "{{ nginx_package }}"
    state: latest
  notify: start_nginx

- name: copy default html file to server
  tags: copy, nginx
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
